title: "atypdev"
icon: "https://images.emojiterra.com/twitter/v14.0/512px/1f3f3-26a7.png"
github: "https://github.com/atypicaldeveloper/breaksh-tblog"
collections:
  authors:
plugins:
  - jekyll-toc
cdn_url: "https://pub-fb004cb3449e4cba91c77c95b0f79e18.r2.dev/images/"