services:
  jekyll:
    build: .
    container_name: jekyll-site
    restart: unless-stopped

    dns:
      - 1.1.1.1
      - 8.8.8.8

    volumes:
      - site-data:/site/_site:ro

  nginx:
    image: nginx:alpine
    container_name: jekyll-nginx
    restart: unless-stopped

    depends_on:
      - jekyll

    volumes:
      - site-data:/usr/share/nginx/html:ro

    ports:
      - "127.0.0.1:8080:80"

volumes:
  site-data:
